name: Evaluate LaunchDarkly flags
on:
  push:
    branches:
      - main
jobs:
  eval-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate flags
        id: ld
        uses: launchdarkly/gha-flags@v0.1.0
        with:
          sdk-key: ${{ secrets.ACCESS_TOKEN }}
          flags: test-boolean-flag,false
            - name:If true
              if:fromJSON(steps.ld.outputs.test-boolean-flag) == true
              run:echo "It's true"
            - name:If false
              if:fromJSON(steps.ld.outputs.test-boolean-flag) == false
              run:echo "It's false"
