name: hello-world
on: push
jobs:
  bash-example:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "Mona The Octocat"
    steps:
      - name: Delete all summary content
      - run: |
            echo "Adding Markdown content that we want to remove before the step ends" >> $GITHUB_STEP_SUMMARY
            rm $GITHUB_STEP_SUMMARY
